# Generated by Django 5.0.3 on 2024-05-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_report_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
    ]
