# Generated by Django 5.0.3 on 2024-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_remove_project_task_projec_title_8cbe2d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="task_projec_user_id_e444db_idx",
        ),
        migrations.RemoveIndex(
            model_name="tag",
            name="task_tag_user_id_077b9a_idx",
        ),
    ]
