# Generated by Django 5.0.3 on 2024-04-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_remove_project_task_projec_user_id_e444db_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateField(null=True),
        ),
    ]
