# Generated by Django 5.0.3 on 2024-04-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_task_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="modified_at",
        ),
    ]
