# Generated by Django 5.0.3 on 2024-05-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
        ("task", "0009_remove_project_modified_at_project_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_projects",
                to="report.report",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_tasks",
                to="report.report",
            ),
        ),
    ]
