# Generated by Django 5.0.3 on 2024-05-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_report_created_at_and_more"),
        ("task", "0010_project_report_task_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="report.report",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="report.report",
            ),
        ),
    ]
