# Generated by Django 5.0.3 on 2024-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_alter_project_report_alter_task_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_schedule",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_schedule_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
